server:
    port: 8081
    error:
        include-message: always
        
spring:
    application:
        name: infraction

    datasource:
        username: leo    
        password: password
        url: jdbc:postgresql://localhost:5432/countryooze #ideally submodule should have own db
        
    jpa:
        hibernate:
            ddl-auto: create-drop #update in production!
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                '[format_sql]': true
        show-sql: true

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
                  