server:
    port: 8761
    error:
        include-message: always
        
spring:
    application:
        name: eureka-server

eureka:
    client:
        fetch-registry: false
        register-with-eureka: false


              